universal array functions

In [1]:
import numpy as np


In [2]:
arr =np.arange(11)

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A = np.random.randn(10) 正态分布？？
A

array([ 0.24957331,  0.19737731, -0.17908797, -0.97125924,  0.76665849,
       -1.69369616, -0.11225009, -0.25738377,  0.87121444,  0.63143262])

In [6]:
B =np.random.randn(10)

In [7]:
B

array([ 0.0316868 ,  0.02067992, -0.41429318,  0.37425681,  1.81930286,
        1.04485144, -0.29459137,  1.63131797, -0.54151735, -0.69507397])

In [8]:
#binary function 
np.add(A,B)


array([ 0.28126011,  0.21805723, -0.59338115, -0.59700243,  2.58596136,
       -0.64884473, -0.40684146,  1.3739342 ,  0.32969709, -0.06364134])

In [10]:
np.maximum(A,B)

array([ 0.24957331,  0.19737731, -0.17908797,  0.37425681,  1.81930286,
        1.04485144, -0.11225009,  1.63131797,  0.87121444,  0.63143262])

In [11]:
np.minimum(A,B)

array([ 0.0316868 ,  0.02067992, -0.41429318, -0.97125924,  0.76665849,
       -1.69369616, -0.29459137, -0.25738377, -0.54151735, -0.69507397])