In [1]:
import numpy as np

In [3]:
arr = np.arange(5)

In [4]:
arr

array([0, 1, 2, 3, 4])

In [5]:
np.save('myarr',arr)

In [6]:
arr=np.arange(10)

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
myarr

NameError: name 'myarr' is not defined

In [10]:
np.load('myarr.npy')

array([0, 1, 2, 3, 4])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1 = np.load('myarr.npy')
arr1

array([0, 1, 2, 3, 4])

In [13]:
arr2=arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [15]:
archive_array=np.load('ziparray.npz')

In [16]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [17]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [20]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')

In [21]:
arr


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])